### ISSUE TITLE
Should this be working with content dimensions?

### ISSUE THREAD

**Issue by kdambekalns** [ttreeagency/Rebirth#1]
I tried this in a site with content dimensions, and it found one orphan (there are more, according to `node:repair`, but those are content nodes).

Upon trying to restore the command said it could not find the Trash node, even though I created one. When giving that nodes identifier as target, it got `Argument 1 passed to Ttree\Rebirth\Service\OrphanNodeService::isValidTargetNode() must implement interface Neos\ContentRepository\Domain\Model\NodeInterface, null given, called in …/Ttree_Rebirth_Service_OrphanNodeService.php on line 90`

So, should this be working with content dimensions? If not, I do not need to spend time debugging this. :)

**Comment by dfeyer** [comment]
Did you have dimensions fallback ? I use it on some project with dimensions, but they all used dimension fallback to a single default language ...

**Comment by kdambekalns** [comment]
Ok, tried again today. It is working, bu you (obviously) need to have a Trash node with a context matching the orphaned nodes to be restored. So, if not using dimension fallbacks you need to make sure a Trash node exists in all dimensipns as needed.
