### ISSUE TITLE
Error when used with Neos 3.0

### ISSUE THREAD

**Issue by kdambekalns** [ttreeagency/Rebirth#2]
Using this with Neos 3.0.

     $ ./flow rebirth:list
    Notice: Undefined property: Ttree\Rebirth\Service\OrphanNodeService::$siteRepository in /…/Neos.Neos/Classes/Controller/CreateContentContextTrait.php line 79

Can be fixed in the trait by using `$this->_siteRepository`, so it could be an error with Neos itself.

**Comment by dfeyer** [comment]
Yes Neos issue

![image](https://user-images.githubusercontent.com/221173/33620976-b7787580-d9e9-11e7-9aba-7fe1a98da752.png)

The trait depend on the availability of siteRepository in the current class ;)

**Comment by dfeyer** [comment]
https://github.com/neos/neos-development-collection/pull/1779

Should fix the issue (was fixed in our fork, but never push for some reason)

**Comment by dfeyer** [comment]
Solved in Neos
